### ISSUE TITLE
Just another location for lxpanel plugins :>

### ISSUE THREAD

**Issue by ghost** [danamlund/cpu-monitor-extension-lxpanel-plugin#1]
Just another location for lxpanel plugins!  :D 
    /usr/lib/i386-linux-gnu/lxpanel/plugins
(using some version of debian which may have dist-upgraded and retained some old things idk)
(Debian 7, i386 now though :> )   

Also, searching for "sensors.so" doesn't help anymores (I just found it with locate lxpanel :> ), but "cpu.so" would've!  :D

**Comment by danamlund** [comment]
I've updated the Makefiles for this and my lxpanel sensors plugin. They should now also try to search for lxpanel plugins in /usr/lib/i386-linux-gnu/lxpanel/plugins and /usr/lib64/i386-linux-gnu/lxpanel/plugins.

I also fixed the typo that it tells you to copy "sensors.so" to the lxpanel plugin directory (it should have said "cpuda.so").

Thank you very much for taking the time to describe how you got it working

**Comment by ghost** [comment]
Cool!   No problem!  :D 

(also there might be different folders for different archs than "i386-linux-gnu", but I dunno what exactly they'd be, not using them myself :>  )

**Comment by danamlund** [comment]
Yes, It also seems those specially-named folders are meant to be for installed libraries that are different from the machine architecture. Maybe its too much of a special case to try and handle all of them correctly (I guess there's a reason autoconf exists). I will just keep it as it is for now.
