### ISSUE TITLE
Arch Linux installation instructions

### ISSUE THREAD

**Issue by rikardfalkeborn** [danamlund/cpu-monitor-extension-lxpanel-plugin#2]
Similar to the lm-sensors package, you could add installation instructions for Arch Linux in the README file, for example:

```
To install in Arch Linux
  Available PKGBUILD in the AUR:
    https://aur.archlinux.org/packages/cpu-monitor-extension-lxpanel-plugin
```

**Comment by danamlund** [comment]
Excellent suggestion, thanks you for letting me know.
The readme have been updated
