### ISSUE TITLE
error while setup (MAKE)

### ISSUE THREAD

**Issue by k1r0s** [danamlund/cpu-monitor-extension-lxpanel-plugin#5]
Linux k1r0s-K52JU 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Lubuntu 14.04

```
gcc -O2 -Wall `pkg-config --cflags glib-2.0 gtk+-2.0` \
	    -shared -fPIC cpuda.c -o cpuda.so \
	    `pkg-config --libs glib-2.0 gtk+-2.0`
cpuda.c: In function ‘cpu_get_info’:
cpuda.c:172:10: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(line, 100, stat);
          ^
cpuda.c: In function ‘cpu_get_cpu_amount’:
cpuda.c:149:13: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
        fgets(line, 100, stat);
             ^

```

Do you need more info?

**Comment by danamlund** [comment]
Those looks like warnings, the compilation should still have worked.
This looks similar to https://github.com/danamlund/cpu-monitor-extension-lxpanel-plugin/issues/4
Does that issue also solve the problem on your system ?

**Comment by k1r0s** [comment]
sry, finally used other extension. :(
